growingio-tracker/src/main/java/com/growingio/android/sdk/track/middleware/DBSQLite.java

https://developer.android.com/reference/java/text/SimpleDateFormat.html
"Y" 仅在API24+支持, 并且表示的是本周所属年份

fix: 大写y仅在API24之后支持

---

growingio-autotracker-core/src/main/java/com/growingio/android/sdk/autotrack/webservices/circle/entity/CircleScreenshot.java

层级通过dfs设置, 理论上应该保证和dispatchDraw的preOrderList一致, 对应方法在API29上设置灰名单, 需要考虑其它方式实现保证在自定义order的情况下zLevel有效

fix: 层级通过dfs设置

---

growingio-tracker-core/src/main/java/com/growingio/android/sdk/track/log/CacheLogger.java
growingio-tracker-core/src/main/java/com/growingio/android/sdk/track/log/CircularFifoQueue.java
growingio-tracker-core/src/main/java/com/growingio/android/sdk/track/log/DebugLogger.java
growingio-tracker-core/src/main/java/com/growingio/android/sdk/track/log/ErrorLogger.java
growingio-tracker-core/src/main/java/com/growingio/android/sdk/track/log/LogItem.java
growingio-tracker-core/src/main/java/com/growingio/android/sdk/track/log/Logger.java
growingio-tracker-core/src/main/java/com/growingio/android/sdk/track/webservices/WebServicesProvider.java
growingio-tracker-core/src/main/java/com/growingio/android/sdk/track/webservices/log/MobileLogService.java
growingio-tracker-core/src/main/java/com/growingio/android/sdk/track/webservices/log/WsLogger.java

adb shell am start -d "growing.d80871b41ef40518://growingio/webservice?openConsoleLog=YES"
参数与iOS保持一致
Log中多线程问题存在的情况比较多, 整体上通过控制CacheLogger获取cache, 性能缺陷应该在CacheLogger的print中, syn如果升级也会导致获取cache阻塞. 
ErrorLogger 不获取cache
WsLogger与DebugLogger通过CAS判断是否获取过cache避免多线程异常, 理论上只需要一个线程输出cache
WsLogger的通过callback发送消息, okhttp的send函数也是synchronized标记的, 建立ws连接后, 调用send也会导致当前日志打印阻塞对应线程
考虑直接封装Logger + Executor主动控制线程, 然后在LogItem中增加Thread信息

feat: 增加urlscheme打开debug

---

growingio-autotracker-core/src/main/java/com/growingio/android/sdk/autotrack/page/PageProvider.java

page判断出现异常直接忽略当前page
parent: com.growingio.android.sdk.autotrack.page.SuperFragment$V4Fragment@4a40584
real parent: ParentFragment{4a40584 #0 id=0x7f091187 android:switcher:2131300743:0}
--------参数-----------
fragment.getUserVisibleHint()false
fragment.getActivity()com.laiyifen.MainActivity@155cafd
fragment.isResumed()true
--------参数-----------
fragment: SubFragment{dd602b #1 id=0x7f091187 android:switcher:2131300743:1}
--------参数-----------
fragment.getUserVisibleHint()true
fragment.getActivity()com.laiyifen.MainActivity@155cafd
fragment.isResumed()true
--------参数-----------

fix: page判断异常

---

demos/demo-autotrack/src/main/java/com/gio/test/three/autotrack/activity/ClickTestActivity.java
demos/demo-autotrack/src/main/res/layout/activity_click_test.xml
demos/demo/src/androidTest/java/com/growingio/autotest/autotracker/ViewClickEventsTest.java
demos/demo/src/androidTest/java/com/growingio/autotest/autotracker/webservices/CircleServiceTest.java
growingio-autotracker-core/src/main/java/com/growingio/android/sdk/autotrack/change/ViewChangeProvider.java
growingio-autotracker-core/src/main/java/com/growingio/android/sdk/autotrack/click/ViewClickProvider.java

满足类似如下场景, 如果代码触发的click事件不进行采集, 仅采集用户行为数据
在oncreate阶段 主动调用click事件 如:RadioGroup默认选择
不提前page的原因, 用户需要在onCreate阶段设置ignore以及alias
虽然可以在super.onCreate之前调用, 但是会带来更大的解释成本

fix: PI-33712 代码触发click在page之前

---

growingio-autotracker-core/src/main/java/com/growingio/android/sdk/autotrack/hybrid/WebViewInjector.java

注入时invoke-static调用virtual方法
java.lang.IncompatibleClassChangeError
The method 'void com.growingio.android.sdk.autotrack.hybrid.WebViewInjector.webkitWebViewLoadDataWithBaseURL(android.webkit.WebView, java.lang.String, java.lang.String, java.lang.String, java.lang.String, java.lang.String)' was expected to be of type static but instead was found to be of type virtual

fix: 注入时invoke-static调用virtual方法

---

gradle/publishAllToMavenLocal.sh
inject-annotation/compiler/src/main/java/com/growingio/sdk/inject/compiler/InjectProcessor.java

workspace如果有空格, 原先获取rootpath的方式为url, 需要使用URLDecode.decode, 否则会导致FileNotFoundException
plugin需要使用到autotracker-core生成的文件, 所以将执行顺序放置到末尾

fix: workspace为url, 特殊字符导致异常

---

growingio-autotracker-gradle-plugin/src/main/java/com/growingio/sdk/plugin/autotrack/AutotrackPlugin.java
growingio-autotracker-gradle-plugin/src/main/java/com/growingio/sdk/plugin/autotrack/compile/AutotrackTransform.java
growingio-network/volley/src/main/java/com/growingio/android/volley/VolleyDataFetcher.java
growingio-tracker-core/src/main/java/com/growingio/android/sdk/track/ipc/MultiProcessDataSharer.java
growingio-tracker-core/src/main/java/com/growingio/android/sdk/track/ipc/ProcessLock.java
growingio-tracker-core/src/main/java/com/growingio/android/sdk/track/middleware/EventSender.java
growingio-tracker-core/src/main/java/com/growingio/android/sdk/track/middleware/EventsSQLite.java
growingio-tracker-core/src/main/java/com/growingio/android/sdk/track/providers/SessionProvider.java
growingio-tracker-core/src/main/java/com/growingio/android/sdk/track/utils/OaidHelper.java
growingio-tracker-core/src/main/java/com/growingio/android/sdk/track/utils/SystemUtil.java
growingio-tracker-core/src/test/java/com/growingio/android/sdk/track/IpcTest.java

优化了一下ProcessLock
Rule S3077 should not apply to references to immutable objects
[Java] Rule S3077 should not apply to references to immutable objects
volatile检测目前依据关键字, 实际是否安全, 对象是否可变需要自己进行判断
Rule S2583 Conditionally executed code should be reachable
Differentiate potentially not nullable values from certainly nullable values
NonNull不能保证运行时安全, 目前认为这是个功能, 不放在短期计划中修改
Rule S2259 Null pointers should not be dereferenced
S2259: Null pointers should not be dereferenced
官方认为跨文件的方法分析比较消耗资源, 所以暂时没有开放该特性

fix: sonarcloud check

---

growingio-tracker-core/src/main/java/com/growingio/android/sdk/track/providers/SessionProvider.java

在Application#onCreate初始化完成后调用setLoginUserId/setLocation触发resendVisit导致timestamp为0

fix: resend时vst的timestamp可能为0

---

demos/demo/src/androidTest/java/com/growingio/autotest/autotracker/PageAttributesEventsTest.java
demos/demo/src/androidTest/java/com/growingio/autotest/autotracker/PageEventsTest.java
demos/demo/src/androidTest/java/com/growingio/autotest/autotracker/ViewClickEventsTest.java
growingio-autotracker-core/src/main/java/com/growingio/android/sdk/autotrack/Autotracker.java
growingio-autotracker-core/src/test/java/com/growingio/android/sdk/autotrack/AutotrackTest.java

在android.enableJetifier=false并且没有依赖support包的情况下, 直接调用trackCustomEvent异常的问题
增加TODO: 用户关联cstm和page相关功能未实现

fix: 区分support包

---

demos/demo/src/androidTest/java/com/growingio/autotest/tracker/SessionEventsTest.java
growingio-tracker-core/src/main/java/com/growingio/android/sdk/Tracker.java
growingio-tracker-core/src/main/java/com/growingio/android/sdk/track/TrackMainThread.java
growingio-tracker-core/src/main/java/com/growingio/android/sdk/track/data/PersistentDataProvider.java
growingio-tracker-core/src/main/java/com/growingio/android/sdk/track/events/base/BaseEvent.java
growingio-tracker-core/src/main/java/com/growingio/android/sdk/track/ipc/IDataSharer.java
growingio-tracker-core/src/main/java/com/growingio/android/sdk/track/ipc/MultiProcessDataSharer.java
growingio-tracker-core/src/main/java/com/growingio/android/sdk/track/ipc/ProcessLock.java
growingio-tracker-core/src/main/java/com/growingio/android/sdk/track/ipc/SharedEntry.java
growingio-tracker-core/src/main/java/com/growingio/android/sdk/track/providers/SessionProvider.java
growingio-tracker-core/src/test/java/com/growingio/android/sdk/track/IpcTest.java
growingio-tracker-core/src/test/java/com/growingio/android/sdk/track/providers/ProviderTest.java

多进程session改变逻辑:
主进程设置用户A - 子进程设置用户B - 主进程设置用户A 触发session改变 发送vst
主进程初始化发送 改变session vst, 子进程发送vst但是使用相同session
disable -> enable 一定会触发发送vst, 但是不会改变session
多进程的datacollect开关相互独立, 但是session共享
统一思想: 
整个应用初始化时只会改变一次session, 发送vst仅在session改变 或者调用enable(开关不会导致session发生变化)
不管子进程还是主进程, 刷新session的逻辑只有如下两个场景:
1. 用户发生改变
2. 后台30s

fix: 多进程问题

---

build.gradle
demos/demo/build.gradle
growingio-autotracker-core/src/main/java/com/growingio/android/sdk/autotrack/page/PageProvider.java
growingio-autotracker-core/src/main/java/com/growingio/android/sdk/autotrack/page/SuperFragment.java

SuperFragment会被ActivityPage持有, 不会在GC时自动回收, ASSOCIATE中SuperFragment持有了Frament的引用, 即导致WeakHashmap中value持有了key的引用, 引发内存泄漏
SuperFragment在demo中不会在GC时自动回收的原因:
1. SuperFragment会被ActivityPage持有, 只要不DestroyView, 就会一直被持有
2. ViewPage的场景, onDestroyView触发后, 在onCreate中设置类似Ignore的SuperFragment此时会被Fragment持有的mView持有, 因为设置了setTag, 然后又被ViewModel持有, 所以与Fragment保持了相同生命周期
复现:
1. 进入无埋点测试->进入NestedFragmentActivity->通过Profile分析, 选择Show activity/fragment Leaks
2. 进入无埋点测试->进入TabFragmentActivity->注释ViewModel相关内容, onCreate中设置Ignore,  切换到Tab5强制GC, 切回Tab1, 发送了Tab1的page(此时SuperFragment被回收, Igore或者Alias设置失效)
测试: 
1. 进入无埋点测试->进入NestedFragmentActivity->通过Profile分析SuperFragment$V4Fragment引用链
2. 进入无埋点测试->进入NestedFragmentActivity->退出NestedFragmentActivity->强制GC, 查看SuperFragment$V4Fragment是否被回收
3. …

fix: memory leak

---

demos/demo-autotrack/src/main/java/com/gio/test/three/autotrack/activity/ui/main/PlaceholderFragment.java
gio-sdk/autotracker-cdp/src/main/java/com/growingio/android/sdk/autotrack/CdpAutotracker.java
gio-sdk/tracker-cdp/src/main/java/com/growingio/android/sdk/track/CdpTracker.java
growingio-autotracker-core/src/main/java/com/growingio/android/sdk/autotrack/Autotracker.java
growingio-autotracker-core/src/main/java/com/growingio/android/sdk/autotrack/change/ViewChangeProvider.java
growingio-autotracker-core/src/main/java/com/growingio/android/sdk/autotrack/page/PageProvider.java
growingio-autotracker-core/src/test/java/com/growingio/android/sdk/autotrack/page/PageTest.java
growingio-tracker-core/src/main/java/com/growingio/android/sdk/Tracker.java
growingio-tracker-core/src/main/java/com/growingio/android/sdk/track/TrackMainThread.java
growingio-tracker-core/src/main/java/com/growingio/android/sdk/track/cdp/CdpEventBuildInterceptor.java
growingio-tracker-core/src/main/java/com/growingio/android/sdk/track/data/PersistentDataProvider.java
growingio-tracker-core/src/main/java/com/growingio/android/sdk/track/providers/SessionProvider.java
growingio-tracker-core/src/main/java/com/growingio/android/sdk/track/providers/UserInfoProvider.java
growingio-webservice/circler/src/main/java/com/growingio/android/circler/CirclerDataLoader.java
growingio-webservice/debugger/src/main/java/com/growingio/android/debugger/DebuggerDataLoader.java

改动点
[✅] 1. postEventToTrackMain中存在判断是否开启采集(isDataCollectionEnabled), 删除多余判断
[✅] 2. 将刷新session移动到判断firstinit的进程锁中, 避免主进程还未刷新session, 子进程发送cstm的场景(从执行上讲, 基本不存在这种场景)
[✅] 3. CdpEventBuildInterceptor中onUserId的回调慢于SessionProvider的onUserId回调 导致事件先于gioId修改发出
[✅] 4. CdpEventBuildInterceptor注册事件拦截晚于业务vst发送, 导致缺失字段
[❌] 5. PersistentProvider 中多进程判断耗时, 转到子线程中执行, 存在问题暂时不进行修改, 在Note 9Pro上初始化耗时在50-70ms之间, 可接受范围内, 暂时不做优化
[✅] 6. 圈选时tipview的内存泄漏并非真正的泄漏, removeView时被leackcanary添加到队列, 然后新的activity#onResume,又重新addView, 此时leakcanary检测view的attachInfo不为null, 认为view泄漏了, 时机推出圈选时tipView可以被回收
[✅] 7. 懒加载debugger和circle的okhttpClient, release环境不需要初始化对应对象
[✅] 8. demo中存在内存泄漏, PlaceholderFragment应该使用this.getViewLifecycleOwner(), 将add/remove与onCreateView/onDestroyView绑定
测试 
1. 断点主进程的refreshSessionId, 子进程调用trackCustomEvent, …

optimize: 删除冗余判断

---

growingio-autotracker-core/src/main/java/com/growingio/android/sdk/autotrack/inject/WebViewInjector.java

复现:
无埋点不初始化SDK, 直接访问带webview的界面, 会引发NPE崩溃
测试:
不初始化无埋点SDK的场景, 可以正常访问界面

fix: 延迟初始化访问导致NPE

---

growingio-autotracker-core/src/main/java/com/growingio/android/sdk/autotrack/Autotracker.java
growingio-hybrid/src/main/java/com/growingio/android/hybrid/HybridBridgeProvider.java
growingio-hybrid/src/main/java/com/growingio/android/hybrid/NativeBridge.java
growingio-tracker-core/src/main/java/com/growingio/android/sdk/Tracker.java

复现
在WebViewActivity中调用GrowingAutotracker.get().bridgeWebView(mWebView);崩溃
WebView需要在初始化对象线程中调用, AOS会检查对应looper引发崩溃
测试
回归埋点、无埋点接口调用

fix: webview looper检查

---

.github/workflows/ci.yml

ndk version from 22.1.7171670 to 23.0.7599858(ANDROID_NDK_LATEST_HOME) in macos-latest
The NdkLocator.kt in gradle plugin 3.5.0 will use the highest version
```kotlin
private fun findNdkPathImpl(
ndkDirProperty: String?,
androidNdkHomeEnvironmentVariable: String?,
sdkFolder: File?,
ndkVersionFromDsl: String?,
getNdkVersionedFolderNames: (File) -> List<String>, // function that returns the NDK folders under $SDK/ndk
getNdkSourceProperties: (File) -> SdkSourceProperties?
): File? {
...
// From the existing NDKs find the highest. We'll use this as a fall-back in case there's an
// error. We still want to succeed the sync and recover as best we can.
val highest = versionedLocations.firstOrNull()
}
fun findNdkPath(
ndkVersionFromDsl: String?,
projectDir: File
): NdkLocatorRecord {
val …
```

fix: ci中ndk环境升级

---

growingio-tracker-core/src/main/java/com/growingio/android/sdk/CoreConfiguration.java
growingio-tracker-core/src/main/java/com/growingio/android/sdk/Tracker.java
growingio-tracker-core/src/main/java/com/growingio/android/sdk/track/ErrorLog.java
growingio-tracker-core/src/main/java/com/growingio/android/sdk/track/data/PersistentDataProvider.java
growingio-tracker-core/src/main/java/com/growingio/android/sdk/track/events/base/BaseEvent.java
growingio-tracker-core/src/main/java/com/growingio/android/sdk/track/ipc/IDataSharer.java
growingio-tracker-core/src/main/java/com/growingio/android/sdk/track/ipc/MultiProcessDataSharer.java
growingio-tracker-core/src/main/java/com/growingio/android/sdk/track/providers/UserInfoProvider.java
growingio-tracker-core/src/test/java/com/growingio/android/sdk/track/providers/ProviderTest.java

1. userKey字段, 存储逻辑与userId相同, 即设置后除非用户主动置null, 否则持久化在本地
2. cleanLoginUserId方法调用时, 会同时清除userKey
3. 调用原先的setLoginUserId(String userId)方法时, 等价于调用setLoginUserId(null, userId)
4. userKey于userId均在设置后所有事件中携带上报
5. userKey改变不会触发事件重发逻辑, userId触发事件重发逻辑保持不变
6. 如果userKey或者userId存在不合法, 直接返回
7. 如果userId为null, 则直接设置userKey与userId均为null

feat: 增加userKey字段

---

growingio-autotracker-core/src/main/java/com/growingio/android/sdk/autotrack/view/ViewHelper.java

menuitem的title存在为null的场景
测试:
不设置bottom_nav_menu.xml的android:title 
然后启动ToolBarActivity 点击左上角为空的的item导致崩溃

fix: menuitem的title如果为null导致npe

---

growingio-tracker-core/src/main/java/com/growingio/android/sdk/track/ipc/MultiProcessDataSharer.java
growingio-tracker-core/src/test/java/com/growingio/android/sdk/track/IpcTest.java

该用例出现的可能为：运行内存中已经保存了相应的key值，但文件上由于未知原因导致该key值未保存或被删除；
解决：由于文件取值返回Object值，故取值都以基本类型的对象取值并加上非空判断。
极难复现
bug修复

remove unboxing and check data is not null

---

CHANGELOG.md
changelog-option.js 

* 增加各个版本changelog
* 增加配置文件解决conventional-changelog忽略merge commit上的tag, 使用changelog-option.js中命令生成changelog文件
测试命令
```
conventional-changelog -p angular -i CHANGELOG.md -s -r 0 -n `pwd`/changelog-option.js\ 注意命令行尾部空格
```
生成CHANGELOG.md是否正常 
* CHANGELOG.md文件生成
无
参考:
https://github.com/conventional-changelog/conventional-changelog/issues/571
https://github.com/conventional-changelog/conventional-changelog/pull/375

build: 增加CHANGELOG

---

growingio-tracker-core/src/main/java/com/growingio/android/sdk/track/utils/NetworkUtil.java
growingio-tracker-core/src/test/java/com/growingio/android/sdk/track/utils/UtilsTest.java

1. 增加网络类型对是否为5G的判断
1. 使用测试机在5G网络下测试，生成事件中的网络类型显示正确
2. 使用测试机在3G、4G等网络下测试，事件中的网络类型显示正确
1. 所有生成事件的网络类型(networkState) 字段
无

fix:网络类型中增加对5g的判断

---

gio-sdk/autotracker-cdp/src/main/java/com/growingio/android/sdk/autotrack/CdpAutotracker.java
gio-sdk/tracker-cdp/src/main/java/com/growingio/android/sdk/track/CdpTracker.java

fix: cdp trackCustomEvent 添加缺失的 eventName 字段验证
当 eventName 为空时，不产生事件
Public API trackCustomEvent() 调用
无

fix: cdp trackCustomEvent add eventName check

---

build.gradle
growingio-autotracker-core/consumer-proguard-rules.pro
growingio-autotracker-gradle-plugin/src/main/java/com/growingio/sdk/plugin/autotrack/compile/ClassRewriter.java
growingio-data/database/src/main/AndroidManifest.xml
growingio-data/database/src/main/java/com/growingio/android/database/DatabaseDataFetcher.java
growingio-data/database/src/main/java/com/growingio/android/database/DatabaseDataLoader.java
growingio-data/database/src/main/java/com/growingio/android/database/DatabaseLibraryModule.java
growingio-data/database/src/main/java/com/growingio/android/database/DeprecatedEventSQLite.java
growingio-data/database/src/main/java/com/growingio/android/database/EventDataContentProvider.java
growingio-data/database/src/main/java/com/growingio/android/database/EventDataManager.java
growingio-data/database/src/main/java/com/growingio/android/database/EventDataSQLiteOpenHelper.java
growingio-data/database/src/main/java/com/growingio/android/database/EventDataTable.java
growingio-data/database/src/test/java/com/growingio/android/database/DbTest.java
growingio-data/protobuf/build.gradle
growingio-data/protobuf/consumer-rules.pro
growingio-hybrid/build.gradle
growingio-tools/oaid/build.gradle
growingio-tools/oaid/consumer-proguard-rules.pro
growingio-tracker-core/consumer-proguard-rules.pro
growingio-tracker-core/proguard-rules.pro
growingio-tracker-core/src/test/java/com/growingio/android/sdk/track/middleware/EventSenderTest.java

1. 对 database 模块重新命名-补充了遗失的android；
2. 检查每个模块的混淆规则；
以release环境情况下测试sdk是否能够正常运行
```
release {
zipAlignEnabled true
minifyEnabled true
shrinkResources true
proguardFiles getDefaultProguardFile('proguard-android.txt'), 'proguard-rules.pro'
signingConfig signingConfigs.release
}
```
需要在混淆情况下全部走一遍测试

添加模块下的混淆规则

---

growingio-autotracker-gradle-plugin/src/main/java/com/growingio/sdk/plugin/autotrack/compile/visitor/InjectAroundClassVisitor.java

发现有的时候添加的插桩配置部分没插桩成功，例如
```java
public class DialogInjector {
@After(clazz = Dialog.class,method = "show")
public static void dialogShow(Dialog alertDialog) {
Log.d("ASMInjector", "\t\n" + Thread.currentThread().getStackTrace()[3].toString() + "\n" + Thread.currentThread().getStackTrace()[2].toString());
}
@After(clazz = DialogInterface.class, method = "dismiss")
public static void dialogDismiss(DialogInterface alertDialog) {
Log.d("ASMInjector", "\t\n" + Thread.currentThread().getStackTrace()[3].toString() + "\n" + Thread.currentThread().getStackTrace()[2].toString());
}
}
```
Dialog.show() 这个插桩配置失效。
分析了下原因，发现是因为[InjectAroundClassVisitor](https://github.com/growingio/growingio-sdk-android-autotracker/blob/fd935718bd3b76ae96bf4b6ff9d46190b6e0120c/growingio-autotracker-gradle-plugin/src/mai …

解决父类重叠的情况下，部分注入点失效的问题

---

growingio-autotracker-core/src/main/java/com/growingio/android/sdk/autotrack/inject/ViewClickProvider.java
growingio-autotracker-core/src/main/java/com/growingio/android/sdk/autotrack/page/PageProvider.java

- fix: findPage getTitle() 增加非空判断
- 原因：穿山甲广告会自己生成一个ActivityWrapper做代理并自己控制生命周期导致sdk的page无法命中，具体类为：PluginFragmentActivityWrapper，且wrapper类并未重载源Activity的getTitle()方法，导致title为空。
- CI 通过
- `activity.getTitle()` 为 null 时，不应该报错
无

fix: findPage getTitle() 增加非空判断

---

demos/demo/src/main/java/com/gio/test/three/DemoApplication.java
growingio-tracker-core/src/main/java/com/growingio/android/sdk/Tracker.java
growingio-tracker-core/src/main/java/com/growingio/android/sdk/track/events/AttributesBuilder.java
growingio-tracker-core/src/main/java/com/growingio/android/sdk/track/events/CustomEvent.java
growingio-tracker-core/src/main/java/com/growingio/android/sdk/track/events/LoginUserAttributesEvent.java
growingio-tracker-core/src/main/java/com/growingio/android/sdk/track/ipc/PersistentDataProvider.java

为了保证模块发送事件时能够拿到sessionid,
将sessionid的设置提前到setup过程中
模块中的session不为空

fix:将sessionid的设置提前到setup过程中

---

build.gradle
growingio-tracker-core/src/main/java/com/growingio/android/sdk/Tracker.java
growingio-tracker-core/src/main/java/com/growingio/android/sdk/track/timer/Timer.java
growingio-tracker-core/src/main/java/com/growingio/android/sdk/track/timer/TimerCenter.java
growingio-tracker-core/src/test/java/com/growingio/android/sdk/track/timer/TimerCenterTest.java
growingio-tracker-core/src/test/java/com/growingio/android/sdk/track/timer/TimerTest.java

更新计时器相关接口，相关逻辑参见技术文档
6个新增接口功能测试
单个timerId仅上报一次事件，事件名称为start接口传入，事件属性为eventDuration，单位为s，保留3位小数精度到ms
关闭sdk采集时，会清除所有timer
endTimer支持设置自定义事件属性
退到后台时会停止计数
新增对外接口
无

feat:timer

---

growingio-tracker-core/src/main/java/com/growingio/android/sdk/track/ipc/MultiProcessDataSharer.java
growingio-tracker-core/src/main/java/com/growingio/android/sdk/track/ipc/PersistentDataProvider.java
growingio-tracker-core/src/main/java/com/growingio/android/sdk/track/ipc/SharedEntry.java

java.lang.NegativeArraySizeException -22345
```shell
16809-22 15:18:33.896 22653 22885 E TRACK.EventDataManager: removeOverdueEvents: deleteNum: 0
16909-22 15:18:33.901 22653 22892 E AndroidRuntime: FATAL EXCEPTION: MultiProcessDataSharer-load
17009-22 15:18:33.901 22653 22892 E AndroidRuntime: Process: com.transsnet.palmpay, PID: 22653
17109-22 15:18:33.901 22653 22892 E AndroidRuntime: java.lang.NegativeArraySizeException: -22345
17209-22 15:18:33.901 22653 22892 E AndroidRuntime: at com.growingio.android.sdk.track.ipc.e.<init>(SharedEntry.java:5)
17309-22 15:18:33.901 22653 22892 E AndroidRuntime: at com.growingio.android.sdk.track.ipc.b.i(MultiProcessDataSharer.java:2)
17409-22 15:18:33.901 22653 22892 E AndroidRuntime: at com.growingio.android.sdk.track.ipc.b.k(MultiProcessDataSharer. …
```

fix: negative array

---

growingio-tracker-core/src/main/java/com/growingio/android/sdk/track/middleware/EventSender.java

多进程情况下，发送Event时出现 “sendEvents: this process can not get lock” 错误日志，导致事件无法发送。
修复：发送事件结束后释放获取到的进程文件锁。
1. 复现多进程下出现的如上错误日志；
2. 修复后不再出现以上错误日志
除了主进程以外的事件发送。

fix:in multi process,after send events should release processLock.

---

build.gradle
demos/demo/build.gradle
growingio-advert/src/main/java/com/growingio/android/advert/AdvertLibraryGioModule.java
growingio-annotation/compiler/src/main/java/com/growingio/sdk/annotation/compiler/ConfigurationGenerator.kt
growingio-apm/src/main/java/com/growingio/android/apm/ApmLibraryGioModule.java
growingio-autotracker-core/src/main/java/com/growingio/android/sdk/autotrack/inject/UtilsInjector.java
growingio-network/okhttp3/src/main/java/com/growingio/android/okhttp3/OkHttpConfig.java
growingio-network/okhttp3/src/main/java/com/growingio/android/okhttp3/OkHttpDataLoader.java
growingio-network/okhttp3/src/main/java/com/growingio/android/okhttp3/OkhttpLibraryGioModule.java
growingio-network/urlconnection/src/main/java/com/growingio/android/urlconnection/UrlConnectionConfig.java
growingio-network/urlconnection/src/main/java/com/growingio/android/urlconnection/UrlConnectionFetcher.java
growingio-network/urlconnection/src/main/java/com/growingio/android/urlconnection/UrlConnectionGioModule.java
growingio-network/volley/src/main/java/com/growingio/android/volley/VolleyConfig.java
growingio-network/volley/src/main/java/com/growingio/android/volley/VolleyDataFetcher.java
growingio-network/volley/src/main/java/com/growingio/android/volley/VolleyLibraryGioModule.java

分别为网络请求添加超时配置，包括Okhttp，UrlConnection和Volley.
Android由于多个Http请求库，所以为每个库添加了设置请求超时的方法。
默认的是OkHttp，接口为`setRequestTimeout(long timeout, TimeUnit unit) `和 `setRequestDetailTimeout(long connectTimeout, long readTimeout, long writeTimeout, TimeUnit unit)`。默认值统一采用okHttp的默认值，10+10+10 = 30s。
URLConnection 默认时间为java的请求时间为 15+15=30s。
Volley 默认为30s.
设置超时时间下限为0，上限为Max.
配置项编译后可以直接通过 `AutotrackConfiguration` 调用。
测试超时机制。

feat:为网络请求添加超时配置

---

growingio-autotracker-core/src/main/java/com/growingio/android/sdk/autotrack/AutotrackConfig.java
growingio-autotracker-core/src/main/java/com/growingio/android/sdk/autotrack/page/FragmentPage.java
growingio-autotracker-core/src/main/java/com/growingio/android/sdk/autotrack/page/SuperFragment.java
growingio-autotracker-core/src/test/java/com/growingio/android/sdk/autotrack/page/PageTest.java

在使用高版本 Navigation 库（2.7.3）时，Navigation库会对所有的导航 Fragment 赋予一个 UUID 生成的随机TAG。为了保证无埋点路径的准确，取消无埋点路径xcontent中对tag的支持，现在默认取 Fragment 的id为xcontent路径。
新增无埋点的配置，若客户需要tag支持，可在配置中打开 `enableFragmentTag(true)`。
测试无埋点Fragment的路径是否正确。
无埋点 Fragment 路径。

fix: fragment tag 存在随机赋值的问题

---

growingio-data/database/src/main/java/com/growingio/android/database/EventDataManager.java
growingio-data/database/src/test/java/com/growingio/android/database/DbTest.java

feat: event data size limit

---

growingio-data/database/src/main/java/com/growingio/android/database/DatabaseDataFetcher.java
growingio-data/database/src/main/java/com/growingio/android/database/EventDataManager.java
growingio-data/database/src/test/java/com/growingio/android/database/DbTest.java
growingio-tracker-core/src/main/java/com/growingio/android/sdk/CoreConfiguration.java
growingio-tracker-core/src/main/java/com/growingio/android/sdk/track/middleware/EventDatabase.java

SDK 添加配置项由于配置数据缓存时间 `setDataValidityPeriod(int days)`.天数不大于30，不小于3.
数据缓存
数据库事件缓存。

feat: data validity period

---

growingio-data/database/src/main/java/com/growingio/android/database/EventDataManager.java

调用ContentProviderClient.release()时在某些机型上（比如oppo）会出现 IBinder 已经释放的情况导致出现空异常。
无，少数案例
部分机型，个例

fix: ContentProviderClient NPE.

---

.github/workflows/pre_release.yml
build.gradle
gradle/libs.versions.toml
growingio-abtest/src/main/java/com/growingio/android/abtest/ABTestDataLoader.java
growingio-abtest/src/main/java/com/growingio/android/abtest/ABTestResponse.java
growingio-annotation/json-serializer/src/main/java/com/growingio/sdk/annotation/json/serializer/JsonFactoryGenerator.kt
growingio-annotation/json-serializer/src/main/java/com/growingio/sdk/annotation/json/serializer/JsonSerializerGenerator.kt
growingio-autotracker-core/src/main/java/com/growingio/android/sdk/autotrack/page/PageProvider.java
growingio-autotracker-core/src/test/java/com/growingio/android/sdk/autotrack/AutotrackTest.java
growingio-data/protobuf/src/main/java/com/growingio/android/protobuf/EventProtocolTransfer.java
growingio-hybrid/src/main/java/com/growingio/android/hybrid/HybridBridgeProvider.java
growingio-hybrid/src/main/java/com/growingio/android/hybrid/HybridConfig.java
growingio-hybrid/src/main/java/com/growingio/android/hybrid/HybridDomLoader.java
growingio-hybrid/src/main/java/com/growingio/android/hybrid/HybridLibraryGioModule.java
growingio-hybrid/src/main/java/com/growingio/android/hybrid/SuperWebView.java
growingio-hybrid/src/main/java/com/growingio/android/hybrid/WebChromeClientDelegate.java
growingio-hybrid/src/main/java/com/growingio/android/hybrid/WebChromeClientX5Delegate.java
growingio-hybrid/src/main/java/com/growingio/android/hybrid/WebViewJavascriptBridgeConfiguration.java
growingio-hybrid/src/test/java/com/growingio/android/hybrid/HybridTest.java
growingio-tracker-core/src/main/java/com/growingio/android/sdk/CoreConfiguration.java
growingio-tracker-core/src/main/java/com/growingio/android/sdk/track/events/base/BaseAttributesEvent.java
growingio-tracker-core/src/main/java/com/growingio/android/sdk/track/middleware/abtest/ABExperiment.java
growingio-tracker-core/src/main/java/com/growingio/android/sdk/track/providers/EventBuilderProvider.java
growingio-tracker-core/src/main/java/com/growingio/android/sdk/track/utils/ReflectUtil.java
growingio-tracker-core/src/main/java/com/growingio/android/sdk/track/view/WindowManagerShadow.java

ABTest 返回的结果中添加实验名称。
上传的实验结果事件中添加实验名称预置属性。

feat: abtest

---

growingio-webservice/circler/src/main/java/com/growingio/android/circler/ThreadSafeTipView.java
growingio-webservice/debugger/src/main/java/com/growingio/android/debugger/ThreadSafeTipView.java

在 minikin.so 的原生代码库中，由于小米等机型有更改系统字体的自定义设置，有概率导致在获取字体集合时出现问题。目前移除在SDK中的圈选和Debugger中的 TipView 初始化避免影响客户的C端用户。
1. 测试圈选和debugger功能不受影响；
2. 使用小米等能设置自定义字体的系统尝试复现；

fix: tipview crash
