- demos/demo-autotrack/src/main/java/com/gio/test/three/autotrack/AutotrackEntryActivity.java
- growingio-autotracker-gradle-plugin/src/main/java/com/growingio/sdk/plugin/autotrack/hook/HookClassesConfig.java
- growingio-autotracker/src/main/java/com/growingio/android/sdk/autotrack/AutotrackConfiguration.java
- growingio-autotracker/src/main/java/com/growingio/android/sdk/autotrack/GrowingAutotracker.java
- growingio-autotracker/src/main/java/com/growingio/android/sdk/autotrack/IGrowingAutotracker.java
- growingio-autotracker/src/main/java/com/growingio/android/sdk/autotrack/IgnorePolicy.java
- growingio-autotracker/src/main/java/com/growingio/android/sdk/autotrack/ImpObserver.java
- growingio-autotracker/src/main/java/com/growingio/android/sdk/autotrack/ImpressionConfig.java
- growingio-autotracker/src/main/java/com/growingio/android/sdk/autotrack/page/PageProvider.java
- growingio-autotracker/src/main/java/com/growingio/android/sdk/autotrack/util/Util.java
- growingio-autotracker/src/main/java/com/growingio/android/sdk/autotrack/util/ViewAttributeUtil.java
> feat: 无埋点 api 对齐，代码checkstyle

- demos/demo-autotrack/src/main/java/com/gio/test/three/autotrack/activity/RecyclerViewImpActivity.java
- growingio-autotracker/src/main/java/com/growingio/android/sdk/autotrack/models/ViewNode.java
- growingio-autotracker/src/main/java/com/growingio/android/sdk/autotrack/view/ViewHelper.java
- growingio-autotracker/src/main/java/com/growingio/android/sdk/autotrack/webservices/circle/CircleService.java
- growingio-autotracker/src/main/java/com/growingio/android/sdk/autotrack/webservices/circle/ViewUtil.java
- growingio-autotracker/src/main/java/com/growingio/android/sdk/autotrack/webservices/circle/entity/CircleScreenshot.java
- growingio-tracker/src/main/java/com/growingio/android/sdk/track/utils/ClassExistHelper.java
增加nodetype
父控件是列表, 子控件继承index
snapshotKey 更新为long
> fix: 圈选部分问题修复

- growingio-autotracker/src/main/java/com/growingio/android/sdk/autotrack/models/ViewNode.java
- growingio-autotracker/src/main/java/com/growingio/android/sdk/autotrack/webservices/circle/entity/ViewElement.java
index 为-1 不再上报, 和hybrid保持一致
Button继承TextView, 区分TEXT和BUTTON时需要做处理
> refactor: index > -1 时才上报， 与hybrid保持一致

- build.gradle
- demos/demo-autotrack/build.gradle
- demos/demo/build.gradle
- gradle.properties
- growingio-autotracker/build.gradle
- growingio-autotracker/consumer-proguard-rules.pro
- growingio-autotracker/gradle.properties
- growingio-tracker/build.gradle
- growingio-tracker/consumer-proguard-rules.pro
- growingio-tracker/gradle.properties
- maven_push.gradle
- publishAutotrackerPluginToMavenLocal.sh
增加发版配置
发布到jcenter 
./gradlew :growingio-tracker:clean growingio-tracker:build :growingio-tracker:bintrayUpload -PbintrayUser=xxx -PbintrayKey=xxx 
发布到nexus
./gradlew :growingio-tracker:clean growingio-tracker:build :growingio-tracker:publishOfficialPublicationToNexusRepository -PbintrayUser=xxx -PbintrayKey=xxx
发布到本地
./gradlew :growingio-tracker:clean growingio-tracker:build :growingio-tracker:publishOfficialPublicationToMavenLocal
发布到build目录单独仓库
./gradlew :growingio-tracker:clean growingio-tracker:build :growingio-tracker:publishOfficialPublicationToBuildRepository
> build: 增加发版配置

- growingio-autotracker/src/main/java/com/growingio/android/sdk/autotrack/models/ViewNode.java
- growingio-autotracker/src/main/java/com/growingio/android/sdk/autotrack/view/ViewHelper.java
- growingio-tracker/src/main/java/com/growingio/android/sdk/track/webservices/log/WsLogger.java
> perf: page按照新的逻辑修改

- demos/demo-autotrack/src/main/res/layout/activity_click_test.xml
- demos/demo/src/androidTest/java/com/growingio/autotest/autotracker/webservices/CircleServiceTest.java
- growingio-autotracker-core/src/main/java/com/growingio/android/sdk/autotrack/webservices/circle/ViewUtil.java
- growingio-autotracker-core/src/main/java/com/growingio/android/sdk/autotrack/webservices/circle/entity/CircleScreenshot.java
- growingio-autotracker-core/src/main/java/com/growingio/android/sdk/autotrack/webservices/circle/entity/ViewElement.java
> fix: change事件无法圈选

- build.gradle
更新版本号3.1.0
增加mobile debugger功能
> build: 更新版本号

- build.gradle
- demos/demo/build.gradle
- gradle.properties
- gradle/publishMaven.gradle
- gradle/stagingMaven.gradle
- growingio-autotracker/gradle.properties
change maven default url
oss.sonatype.org -> s01.oss.sonatype.org
> change maven default url

- growingio-autotracker-gradle-plugin/src/main/java/com/growingio/sdk/plugin/autotrack/compile/visitor/InjectSuperClassVisitor.java
- growingio-autotracker-gradle-plugin/src/main/java/com/growingio/sdk/plugin/autotrack/hook/TargetClass.java
调用接口的方法, 在dx阶段会导致异常
Uncaught translation error:
com.android.dx.cf.code.SimException: default or static interface method used without --min-sdk-version >= 24
> fix: SimException: default or static interface method

- .github/workflows/build.yml
- build.gradle
> update: 更新版本为3.1.0

- build.gradle
> upgrade version to 3.2.0

- growingio-autotracker-core/src/main/java/com/growingio/android/sdk/autotrack/hybrid/HybridBridgeProvider.java
- 修复无埋点注入未初始化时，跳转webview注入崩溃的问题
> fix: 修复未初始化时，webview注入崩溃的问题

- growingio-tracker-core/src/main/java/com/growingio/android/sdk/Tracker.java
- growingio-tracker-core/src/main/java/com/growingio/android/sdk/track/providers/SessionProvider.java
> fix: 数据采集接口设置无效

- growingio-autotracker-core/src/main/java/com/growingio/android/sdk/autotrack/page/PageProvider.java
测试方式, 延迟初始化到特定activity
activity#onresume后初始化sdk, 并嵌套显示fragment
> fix: activityPage为空

- gio-sdk/tracker-cdp/src/main/java/com/growingio/android/sdk/track/GrowingAppModule.java
> fix: api保持一致

- growingio-tracker-core/src/main/java/com/growingio/android/sdk/track/webservices/log/WsLogger.java
> fix: debugger 不发送logger_data

- build.gradle
> update: 更新版本号为3.2.1

- build.gradle
> update: 更新版本号为3.2.2

- .github/workflows/publish_manual.yml
添加在PR合并前，可以手动触发maven发布的workflow，用于测试
无
无
无
> ci: action添加手动对非master分支的maven发布流

- build.gradle
* 更新版本号为3.3.1-11111-SNAPSHOT
无
无
无
> build: 更新版本号为3.3.1-11111-SNAPSHOT

- build.gradle
> update: 更新版本号为3.3.2

- gio-sdk/autotracker-cdp/src/main/java/com/growingio/android/sdk/autotrack/CdpEventBuildInterceptor.java
- gio-sdk/tracker-cdp/src/main/java/com/growingio/android/sdk/track/CdpEventBuildInterceptor.java
- growingio-data/database/src/test/java/com/growingio/database/DbTest.java
- growingio-hybrid/src/test/java/com/growingio/android/hybrid/HybridTest.java
- growingio-tools/crash/src/test/java/com/growingio/android/crash/CrashTest.java
- growingio-tracker-core/src/main/java/com/growingio/android/sdk/Tracker.java
- growingio-tracker-core/src/main/java/com/growingio/android/sdk/track/ipc/MultiProcessDataSharer.java
- growingio-tracker-core/src/main/java/com/growingio/android/sdk/track/ipc/ProcessLock.java
- growingio-tracker-core/src/main/java/com/growingio/android/sdk/track/ipc/SharedEntry.java
- growingio-tracker-core/src/main/java/com/growingio/android/sdk/track/providers/DeviceInfoProvider.java
- growingio-tracker-core/src/main/java/com/growingio/android/sdk/track/providers/UserInfoProvider.java
- growingio-tracker-core/src/test/java/com/growingio/android/sdk/track/IpcTest.java
- growingio-tracker-core/src/test/java/com/growingio/android/sdk/track/providers/ProviderTest.java
- growingio-tracker-core/src/test/java/com/growingio/android/sdk/track/webservice/WebServiceTest.java
- growingio-webservice/circler/src/test/java/com/growingio/android/circler/CirclerTest.java
- growingio-webservice/circler/src/test/java/com/growingio/android/circler/ScreenShotTest.java
- growingio-webservice/debugger/src/test/java/com/growingio/android/debugger/DebuggerTest.java
- growingio-webservice/debugger/src/test/java/com/growingio/android/debugger/ScreenShotTest.java
- inject-annotation/compiler/src/main/java/com/growingio/sdk/inject/compiler/AnnotationUtil.java
- 修改Sonar上提示的bug，优先解决比较严重的bug
- 需要将修改的部分与相应的bug进行对应，测试比对结果是否正常。大部分bug都比较容易判断
- 主要影响代码的质量检查指标，原则上对业务逻辑不会产生影响
> fix:解决sonar上提示的bug

- .github/workflows/ci.yml
- growingio-autotracker-gradle-plugin/src/main/java/com/growingio/sdk/plugin/autotrack/compile/visitor/InjectSuperClassVisitor.java
- growingio-webservice/circler/src/main/java/com/growingio/android/circler/WebSocketHandler.java
> allow skip sonarqube

- .github/workflows/ci.yml
- build.gradle
- demos/demo-autotrack/src/main/java/com/gio/test/three/autotrack/activity/DialogTestActivity.java
- demos/demo-autotrack/src/main/java/com/gio/test/three/autotrack/activity/WebViewActivity.java
- demos/demo-autotrack/src/main/java/com/gio/test/three/autotrack/activity/X5WebViewActivity.java
- demos/demo-autotrack/src/main/res/layout/activity_dialog_test.xml
- demos/demo-autotrack/src/main/res/layout/activity_web_view.xml
- demos/demo/src/androidTest/java/com/growingio/autotest/autotracker/impression/ImpressionEventsTest.java
- demos/demo/src/androidTest/java/com/growingio/autotest/tracker/IdMappingTest.java
- growingio-hybrid/src/main/java/com/growingio/android/hybrid/HybridBridgeLoader.java
- growingio-hybrid/src/main/java/com/growingio/android/hybrid/HybridBridgeProvider.java
- growingio-hybrid/src/main/java/com/growingio/android/hybrid/HybridDomLoader.java
- growingio-tracker-core/build.gradle
- growingio-tracker-core/src/main/java/com/growingio/android/sdk/track/view/ViewTreeStatusProvider.java
- growingio-webservice/circler/src/main/java/com/growingio/android/circler/screenshot/CircleScreenshot.java
- growingio-webservice/circler/src/main/java/com/growingio/android/circler/screenshot/ScreenshotProvider.java
- growingio-webservice/circler/src/test/java/com/growingio/android/circler/ScreenShotTest.java
- growingio-webservice/debugger/src/main/java/com/growingio/android/debugger/DebuggerScreenshot.java
- growingio-webservice/debugger/src/main/java/com/growingio/android/debugger/ScreenshotProvider.java
1. 修复圈选时若存在webview导致生成截图失败；
2. 避免当屏幕刷新过快时导致圈选截图事件不断被取消的问题；
1.  测试在原生+webview界面是否能正常圈选；
2. 在不停动画的界面上能否正常圈选；
圈选和Debugger
> fix circler webview bug

- growingio-adapter/analytics-ga/.gitignore
- growingio-adapter/analytics-ga/build.gradle
- growingio-adapter/analytics-ga/src/main/java/com/growingio/android/analytics/google/GoogleAnalyticsAdapter.java
- growingio-adapter/analytics-ga/src/test/java/com/growingio/android/analytics/google/GoogleAnalyticsAdapterTest.java
- growingio-adapter/analytics-ga/src/test/resources/res/xml/global_tracker.xml
- growingio-data/database/src/main/java/com/growingio/android/database/EventDataManager.java
- growingio-tracker-core/src/main/java/com/growingio/android/sdk/track/TrackMainThread.java
- growingio-tracker-core/src/main/java/com/growingio/android/sdk/track/utils/SysTrace.java
GA Adapter 增加单测
执行单测，能够正常通过
单测
> feat: 增加单测

- .github/workflows/publish_module.yml
- build.gradle
- gradle/existDenpendices.gradle
更新单独模块上传的脚本，使其能正常运行。
测试单模块能否正常打包
考虑了下，为了方便用户集成，3.0 Android SDK相关的版本还是统一控制，像 giokit，upgrade这些库的版本可以考虑通过 platform-bom 来进行依赖管理
> feat:更新单独模块上传的脚本

- build.gradle
> feat: release 3.4.2

- build.gradle
- growingio-sdk-bom/build.gradle
- growingio-sdk-bom/publishMaven.gradle
bom 版本号还是与主SDK版本一致； 
bom 下的依赖自读取；
xx-adapter 不会随着版本号升级，固定版本号；
测试 bom 依赖版本
bom的依赖方式
> fix bom version

- build.gradle
> Release3.4.3

- .github/workflows/publish.yml
- .github/workflows/publish_manual.yml
- .github/workflows/publish_module.yml
> update publish yml

- demos/demo/src/androidTest/java/com/growingio/autotest/autotracker/ViewClickEventsTest.java
- growingio-autotracker-core/src/main/java/com/growingio/android/sdk/autotrack/view/ViewHelper.java
- growingio-autotracker-core/src/main/java/com/growingio/android/sdk/autotrack/view/ViewNode.java
- growingio-autotracker-core/src/test/java/com/growingio/android/sdk/autotrack/view/ViewNodeTest.java
- growingio-webservice/circler/src/main/java/com/growingio/android/circler/screenshot/CircleScreenshot.java
xpath计算参考文档
https://growingio.atlassian.net/wiki/spaces/SDK/pages/1213792924/SDK+3.0+Page
> fix:circle计算xpath异常

- growingio-tracker-core/src/main/java/com/growingio/android/sdk/track/timer/TimerCenter.java
- growingio-tracker-core/src/test/java/com/growingio/android/sdk/track/timer/TimerCenterTest.java
> optimize: rename eventDuration

- build.gradle
> release 3.4.5

- build.gradle
- demos/demo/src/androidTest/java/com/growingio/autotest/autotracker/webservices/CircleServiceTest.java
- demos/demo/src/androidTest/java/com/growingio/autotest/autotracker/webservices/DebuggerServiceTest.java
- demos/demo/src/main/AndroidManifest.xml
- demos/demo/src/main/java/com/gio/test/three/DemoApplication.java
- demos/demo/src/main/java/com/gio/test/three/core/TrackActivity.java
> release 3.4.6

- growingio-advert/src/main/java/com/growingio/android/advert/AdvertActivateDataLoader.java
- growingio-tracker-core/src/main/java/com/growingio/android/sdk/track/providers/SessionProvider.java
发送激活事件前确认是否需要更新session
判断 激活 事件session与 visit事件一致
激活事件
> fix:check seesion before send activate event.

- build.gradle
- growingio-hybrid/src/main/java/com/growingio/android/hybrid/HybridBridgeProvider.java
- growingio-hybrid/src/main/java/com/growingio/android/hybrid/HybridDomLoader.java
修复Flutter圈选情况下 webview 调用js不再主线程的问题。
测试圈选时不再崩溃的情况
> All WebView methods must be called on the same thread.

- build.gradle
- growingio-autotracker-core/src/main/java/com/growingio/android/sdk/autotrack/AutotrackConfig.java
- growingio-autotracker-core/src/main/java/com/growingio/android/sdk/autotrack/AutotrackOptions.java
- growingio-autotracker-core/src/main/java/com/growingio/android/sdk/autotrack/inject/UcWebViewInjector.java
- growingio-autotracker-core/src/main/java/com/growingio/android/sdk/autotrack/inject/WebViewInjector.java
- growingio-autotracker-core/src/main/java/com/growingio/android/sdk/autotrack/inject/X5WebViewInjector.java
- growingio-autotracker-core/src/test/java/com/growingio/android/sdk/autotrack/hybrid/HybridTest.java
增加WebViewBridgeEnabled配置项
WebViewBridgeEnabled为false时，需要手动bridgeForWebview支持webview打通
> feat: add WebViewBridgeEnabled

- .github/workflows/pre_release.yml
- gradle/libs.versions.toml
- growingio-hybrid/src/main/java/com/growingio/android/hybrid/HybridBridgeProvider.java
- growingio-hybrid/src/main/java/com/growingio/android/hybrid/HybridConfig.java
- growingio-hybrid/src/main/java/com/growingio/android/hybrid/HybridDomLoader.java
- growingio-hybrid/src/main/java/com/growingio/android/hybrid/HybridLibraryGioModule.java
- growingio-hybrid/src/main/java/com/growingio/android/hybrid/SuperWebView.java
- growingio-hybrid/src/main/java/com/growingio/android/hybrid/WebChromeClientDelegate.java
- growingio-hybrid/src/main/java/com/growingio/android/hybrid/WebChromeClientX5Delegate.java
- growingio-hybrid/src/main/java/com/growingio/android/hybrid/WebViewJavascriptBridgeConfiguration.java
- growingio-hybrid/src/test/java/com/growingio/android/hybrid/HybridTest.java
- growingio-tracker-core/src/main/java/com/growingio/android/sdk/track/utils/ReflectUtil.java
- growingio-tracker-core/src/main/java/com/growingio/android/sdk/track/view/WindowManagerShadow.java
在无埋点SDK初始化中设置：`setAutoJsSdkInject(true)` 将会自动将  webjs sdk 加载至所有的webview中。
> feat: auto inject js sdk in webview.

- gradle/libs.versions.toml
- growingio-abtest/src/main/java/com/growingio/android/abtest/ABTestDataLoader.java
- growingio-annotation/compiler/src/main/java/com/growingio/sdk/annotation/compiler/AppModuleGenerator.java
- growingio-tracker-core/src/main/java/com/growingio/android/sdk/track/TrackMainThread.java
- growingio-tracker-core/src/main/java/com/growingio/android/sdk/track/log/ErrorLogger.java
- growingio-tracker-core/src/main/java/com/growingio/android/sdk/track/providers/PersistentDataProvider.java
AB测试模块在判断为新设备时添加 newDevice 的请求参数。
是否为新设备的判断规则为：在第一次获取 DeviceId 时的同一进程中,session 相同时。
如上测试
ABTest模块
> feat:AB测试模块添加newDevice 参数

- .github/workflows/ci.yml
- .github/workflows/pre_release.yml
- .github/workflows/publish.yml
- .github/workflows/publish_manual.yml
- .github/workflows/publish_module.yml
- gradle/libs.versions.toml
> upgrade version to 4.5.0
